name: backoff
description: The exponential backoff algorithm in Dart
version: 1.0.1
repository: https://github.com/iamEtornam/backoff

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.12
